name: 'BinPar Deploy ECS Service Action for GitHub Actions'
description: 'Registers an Amazon ECS task definition, and deploys it to a service, but with more options.'
author: 'Marcos González <marcos@binpar.com>'
icon: 'upload-cloud'
color: 'orange'

# Define your inputs here.
inputs:
  task-definition:
    description: 'The path to the ECS task definition file to register.'
    required: true
  services-definition:
    description: 'The path to the YAML with the services definition.'
    required: true
  region:
    description: 'The AWS region to use.'
    required: false
  wait-for-service-stability:
    description: 'Wait for the service to be stable before continuing.'
    required: false
    default: false
  wait-for-minutes:
    description: 'The number of minutes to wait for the service to be stable.'
    required: false
    default: 10
  force-new-deploy:
    description: 'Force a new deployment of the service.'
    required: false
    default: true

# Define your outputs here.
outputs:
  task-definition-arn:
    description: 'The ARN of the task definition.'

runs:
  using: node18
  main: dist/index.js
